### ISSUE TITLE
keep CamelCase for classes

### ISSUE THREAD

**Issue by dridk** [ikit/cytosnap#7]
probably an error from myself... 
[Here](https://github.com/ikit/Cytosnap/blob/master/app.py#L38) and [Here](https://github.com/ikit/Cytosnap/blob/master/app.py#L46) you have defined function in CamelCase. It should be under_score. 

```
def error_response():
  pass 
```

**Comment by ikit** [comment]
ok done

**Comment by dridk** [comment]
You should close your issue from your commit message . 
Just type : #fix issueNumber
