### ISSUE TITLE
use authentification decorator

### ISSUE THREAD

**Issue by dridk** [ikit/cytosnap#8]
It seems you check authentification for all request. 
From my point of view, It's better to use decorator for reach necessary endpoint. 

```
 @app.route('/images/')
 @check_auth 
 def get_images():
     pass
```

**Comment by ikit** [comment]
From my point of view, authent must be checked for each request. Basic principle of security.

**Comment by dridk** [comment]
ok ! But that's mean only authentifed user will be able to use your API . You are not doing a public/Protected API. You are doing a full Protected API. But I am okay ! 
Be sure all non-auth request will return you : " authentification required "
